packages:
  - "packages/*"
  - "packages/plugins/*"
  - "apps/*"
  - "examples/*"

catalog:
  # Shared dependencies across workspace
  typescript: ^5.8.3
  "@types/node": ^22
  zod: ^3.24.4

  # Framework specific dependencies
  "@modelcontextprotocol/sdk": ^1.17.4
  "@swc/core": "^1.11.24"
  "@types/express": "^5.0.1"
  "@types/webpack-node-externals": "^3.0.4"
  "chalk": "^5.3.0"
  "chokidar": "^3.6.0"
  "clean-webpack-plugin": "^4.0.0"
  "commander": "^11.1.0"
  "content-type": "^1.0.5"
  "cross-env": "^7.0.3"
  "del": "^7.0.0"
  "dotenv": "^16.5.0"
  "express": "^4.19.1"
  "fork-ts-checker-webpack-plugin": "^8.0.0"
  "fs-extra": "^11.3.0"
  "glob": "^11.0.2"
  "json5": "^2.2.3"
  "jsonwebtoken": "^9.0.2"
  "memfs": "^4.17.2"
  "raw-body": "^3.0.0"
  "swc-loader": "^0.2.6"
  "tsx": "^4.19.4"
  "webpack": "^5.99.7"
  "webpack-node-externals": "^3.0.0"
  "webpack-virtual-modules": "^0.5.0"

  # Development dependencies
  "@types/content-type": "^1.1.9"
  "@types/fs-extra": "^11.0.4"
  "@types/jsonwebtoken": "^9.0.9"
  "copy-webpack-plugin": "^12.0.2"
  "node-loader": "^1.0.1"

  # init-xmcp specific dependencies
  "inquirer": "^9.2.12"
  "ora": "^7.0.1"
  "@types/inquirer": "^9.0.7"

  # create-xmcp-app specific dependencies
  "@types/ora": "^3.1.0"
