import { describe, it, expect } from "vitest";
import path from "node:path";
import fs from "node:fs/promises";
import { buildFixture, fixturePath, snapshotFileTree } from "./_utils";

// `xmcp build --cf` writes the bundled Workers entry to `<root>/worker.js`
// and a wrangler config to `<root>/wrangler.jsonc` (only if the user does
// not already have wrangler.toml/jsonc). The bundle is generated by rspack
// into `.xmcp/cloudflare/worker.js` first; the platform step copies it out.
// Source: packages/xmcp/src/platforms/build-cloudflare-output.ts.
describe("adapter — cloudflare", () => {
  const FIXTURE = "cloudflare-output";

  it("emits worker.js and wrangler.jsonc at the fixture root", async () => {
    const result = await buildFixture(FIXTURE, {
      args: ["--cf"],
      cleanPaths: ["worker.js", "wrangler.jsonc", ".xmcp"],
    });
    expect(
      result.exitCode,
      `cloudflare build failed:\n${result.stderrChunks.join("")}\n${result.stdoutChunks.join("")}`
    ).toBe(0);

    const fixtureDir = fixturePath(FIXTURE);
    const workerPath = path.join(fixtureDir, "worker.js");
    const wranglerPath = path.join(fixtureDir, "wrangler.jsonc");

    await expect(fs.access(workerPath)).resolves.toBeUndefined();
    await expect(fs.access(wranglerPath)).resolves.toBeUndefined();

    // Sanity: worker bundle is non-empty and references the exported fetch
    // handler — that's what Workers actually invokes.
    const worker = await fs.readFile(workerPath, "utf8");
    expect(worker.length).toBeGreaterThan(0);
    expect(worker).toMatch(/fetch/);

    // wrangler.jsonc generated by xmcp pins the bundled worker as the entry
    // and uses the project name from package.json.
    const wrangler = await fs.readFile(wranglerPath, "utf8");
    expect(wrangler).toMatch(/"main":\s*"worker\.js"/);
    expect(wrangler).toMatch(/"compatibility_flags":\s*\[\s*"nodejs_compat"\s*\]/);

    // Snapshot the .xmcp/ build tree so accidental drift in the cloudflare
    // bundle layout (added chunks, renamed entry) is caught even when the
    // explicit assertions above still pass. Update with `pnpm test -u` when
    // the change is intentional.
    const xmcpTree = await snapshotFileTree(path.join(fixtureDir, ".xmcp"));
    expect(xmcpTree).toMatchSnapshot();
  }, 90_000);
});
