import path from "path";
import fs from "fs";

const rootDir = process.cwd();

/**
 * Build the Cloudflare Workers output structure.
 * Creates a .cloudflare directory with:
 * - worker.js - The bundled Cloudflare Worker
 * - wrangler.toml - Wrangler configuration template
 */
async function buildCloudflareOutput() {
  const outputDir = path.join(rootDir, ".cloudflare");
  const adapterDir = path.join(rootDir, ".xmcp", "adapter");

  console.log("Building Cloudflare Workers output structure...");

  // Create output directory
  fs.mkdirSync(outputDir, { recursive: true });

  // Check if adapter output exists
  const sourceFile = path.join(adapterDir, "index.js");
  if (!fs.existsSync(sourceFile)) {
    throw new Error(
      "Adapter output not found. Make sure experimental.adapter is set to 'cloudflare' in your xmcp.config.ts"
    );
  }

  // Copy the bundled worker
  const targetFile = path.join(outputDir, "worker.js");
  fs.copyFileSync(sourceFile, targetFile);

  // Generate wrangler.toml template
  const projectName = getProjectName();
  const wranglerConfig = generateWranglerConfig(projectName);
  fs.writeFileSync(path.join(outputDir, "wrangler.toml"), wranglerConfig);

  console.log("Cloudflare Workers output structure created successfully");
  console.log("");
  console.log("Next steps:");
  console.log("  1. cd .cloudflare");
  console.log("  2. npx wrangler dev       # Test locally");
  console.log("  3. npx wrangler deploy    # Deploy to Cloudflare");
}

/**
 * Get the project name from package.json or directory name.
 */
function getProjectName(): string {
  try {
    const packageJsonPath = path.join(rootDir, "package.json");
    if (fs.existsSync(packageJsonPath)) {
      const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf-8"));
      if (packageJson.name) {
        // Sanitize the name for Cloudflare Workers
        return packageJson.name
          .replace(/^@[^/]+\//, "") // Remove scope
          .replace(/[^a-zA-Z0-9-]/g, "-") // Replace invalid chars
          .toLowerCase();
      }
    }
  } catch {
    // Fallback to directory name
  }

  return path.basename(rootDir).replace(/[^a-zA-Z0-9-]/g, "-").toLowerCase();
}

/**
 * Generate a wrangler.toml configuration file.
 */
function generateWranglerConfig(projectName: string): string {
  return `# Wrangler configuration for Cloudflare Workers
# Generated by xmcp build --cf
# For more options, see: https://developers.cloudflare.com/workers/wrangler/configuration/
#
# Note: You may see a warning about "suspicious-nullish-coalescing" during
# wrangler dev/deploy. This is a false positive from minified dependency code
# (zod/MCP SDK) and can be safely ignored - it doesn't affect functionality.

name = "${projectName}"
main = "worker.js"
compatibility_date = "${new Date().toISOString().split("T")[0]}"
compatibility_flags = ["nodejs_compat"]

# Uncomment to add environment variables
# [vars]
# MY_VAR = "my-value"

# Uncomment to add secrets (set via wrangler secret put)
# [[secrets]]
# name = "MY_SECRET"

# Uncomment to add KV namespaces
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-namespace-id"

# Uncomment to add D1 databases
# [[d1_databases]]
# binding = "MY_DB"
# database_name = "my-database"
# database_id = "your-database-id"

# Uncomment for custom domain routing
# [[routes]]
# pattern = "example.com/api/*"
# zone_name = "example.com"
`;
}

export { buildCloudflareOutput };
