import path from "path";
import fs from "fs-extra";

const DEFAULT_WRANGLER_VERSION = "^4.61.1";
const DEFAULT_WORKERS_TYPES_VERSION = "^4.20241112.0";

function sanitizeWorkerName(name: string): string {
  return name
    .replace(/^@[^/]+\//, "")
    .replace(/[^a-zA-Z0-9-]/g, "-")
    .toLowerCase();
}

function getProjectName(projectPath: string): string {
  try {
    const packageJsonPath = path.join(projectPath, "package.json");
    if (fs.existsSync(packageJsonPath)) {
      const packageJson = fs.readJsonSync(packageJsonPath);
      if (packageJson.name) {
        return sanitizeWorkerName(packageJson.name);
      }
    }
  } catch {
    // fall back to directory name
  }

  return sanitizeWorkerName(path.basename(projectPath));
}

function ensureWranglerConfig(projectPath: string): void {
  const wranglerTomlPath = path.join(projectPath, "wrangler.toml");
  const wranglerJsoncPath = path.join(projectPath, "wrangler.jsonc");
  if (fs.existsSync(wranglerTomlPath) || fs.existsSync(wranglerJsoncPath)) {
    return;
  }

  const projectName = getProjectName(projectPath);
  const compatibilityDate = new Date().toISOString().split("T")[0];

  const wranglerConfig = `{
  "$schema": "node_modules/wrangler/config-schema.json",
  // Wrangler config generated by: create-xmcp-app --cloudflare
  // Docs: https://developers.cloudflare.com/workers/wrangler/configuration/
  "name": ${JSON.stringify(projectName)},
  "main": "worker.js",
  "compatibility_date": ${JSON.stringify(compatibilityDate)},
  "compatibility_flags": ["nodejs_compat"],

  // Observability (Workers Logs)
  "observability": {
    "enabled": true
  }
}
`;

  fs.writeFileSync(wranglerJsoncPath, wranglerConfig);
}

function ensureTsConfig(projectPath: string): void {
  const tsconfigPath = path.join(projectPath, "tsconfig.json");
  if (!fs.existsSync(tsconfigPath)) {
    return;
  }

  const tsconfig = fs.readJsonSync(tsconfigPath);
  tsconfig.compilerOptions = tsconfig.compilerOptions ?? {};

  if (!Array.isArray(tsconfig.compilerOptions.types)) {
    return;
  }

  const types: string[] = tsconfig.compilerOptions.types;

  if (!types.includes("@cloudflare/workers-types")) {
    types.push("@cloudflare/workers-types");
  }

  tsconfig.compilerOptions.types = types;

  fs.writeJsonSync(tsconfigPath, tsconfig, { spaces: 2 });
}

export function applyCloudflareSettings(projectPath: string): void {
  const packageJsonPath = path.join(projectPath, "package.json");
  if (fs.existsSync(packageJsonPath)) {
    const packageJson = fs.readJsonSync(packageJsonPath);

    packageJson.scripts = packageJson.scripts ?? {};
    packageJson.scripts.build = "xmcp build --cf";
    if (!packageJson.scripts.dev || packageJson.scripts.dev === "xmcp dev") {
      packageJson.scripts.dev = "xmcp dev --cf & npx wrangler dev";
    }
    packageJson.scripts.deploy =
      packageJson.scripts.deploy ?? "npx wrangler deploy";
    packageJson.scripts.preview =
      packageJson.scripts.preview ?? "npx wrangler dev";

    if (!packageJson.type) {
      packageJson.type = "module";
    }

    packageJson.devDependencies = packageJson.devDependencies ?? {};
    packageJson.devDependencies.wrangler =
      packageJson.devDependencies.wrangler ?? DEFAULT_WRANGLER_VERSION;
    packageJson.devDependencies["@cloudflare/workers-types"] =
      packageJson.devDependencies["@cloudflare/workers-types"] ??
      DEFAULT_WORKERS_TYPES_VERSION;

    fs.writeJsonSync(packageJsonPath, packageJson, { spaces: 2 });
  }

  ensureWranglerConfig(projectPath);
  ensureTsConfig(projectPath);
}
