import type { ServerContext } from "@modelcontextprotocol/server";
import type { McpClientInfo } from "../../types/client-info";
import { createContext } from "../../utils/context";
import { getHttpRequestContext } from "./http-request-context";

export interface RequestContext {
  readonly clientInfo?: Readonly<McpClientInfo>;
  readonly http?: {
    /** The HTTP request ID generated by xmcp, not the JSON-RPC message ID. */
    readonly id: string;
    readonly headers: Readonly<
      Record<string, string | readonly string[] | undefined>
    >;
  };
  /** The live cancellation signal supplied by the MCP SDK. */
  readonly signal: AbortSignal;
}

// Reuse the shared context registry so bundled handlers and the runtime see
// the same scope, without retaining the last request for out-of-scope reads.
const requestContext = createContext<RequestContext>({
  name: "request-context",
  fallback: false,
});

/** Read the current tool request from a handler or one of its async helpers. */
export function getRequestContext(): RequestContext {
  try {
    return requestContext.getContext();
  } catch {
    throw new Error(
      "getRequestContext() can only be used while handling a tool request."
    );
  }
}

/** Internal boundary around user tool execution; handler arguments stay intact. */
export function withRequestContext<T>(
  ctx: ServerContext,
  clientInfo: McpClientInfo | undefined,
  callback: () => T
): T {
  let http: RequestContext["http"];
  // STDIO must never read an HTTP context's legacy fallback value.
  if (ctx.http) {
    const request = getHttpRequestContext();
    const headers = Object.fromEntries(
      Object.entries(request.headers).map(([key, value]) => [
        key,
        Array.isArray(value) ? Object.freeze([...value]) : value,
      ])
    );
    http = Object.freeze({
      id: request.id,
      headers: Object.freeze(headers),
    });
  }
  return requestContext.provider(
    Object.freeze({
      clientInfo: clientInfo ? Object.freeze({ ...clientInfo }) : undefined,
      http,
      signal: ctx.mcpReq.signal,
    }),
    callback
  );
}
