/**
 * OpenAI tool invocation metadata
 */
export interface OpenAIToolInvocation {
  /**
   * Message displayed while the tool is executing
   * @example "Hand-tossing a map..."
   */
  invoking?: string;

  /**
   * Message displayed after the tool completes
   * @example "Served a fresh map!"
   */
  invoked?: string;
}

/** OpenAI metadata for MCP tools.*/
export interface OpenAIMetadata {
  /** Tool invocation status messages */
  toolInvocation?: OpenAIToolInvocation;

  /**
   * Whether the widget is accessible in the UI
   * @default true
   */
  widgetAccessible?: boolean;

  /**
   * Whether the result can produce a widget
   * @default true
   */
  resultCanProduceWidget?: boolean;

  /**
   * Widget output template URI (auto-generated by framework)
   * @internal Framework sets this automatically as "ui://widget/{tool-name}.html"
   * Do not set this manually unless you need a custom path
   * @example "ui://widget/custom-path.html"
   */
  // remove it for now to prevent confusion
  //outputTemplate?: string;
}
