"use client";
import {
  type ComponentProps,
  createContext,
  type HTMLAttributes,
  type ReactNode,
  type RefObject,
  useContext,
  useRef,
  useEffect,
  useState,
} from "react";
import { cn } from "@/lib/cn";
import { CopyButton as CustomCopyButton } from "./ui/copy-button";

export interface CodeBlockProps extends ComponentProps<"figure"> {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  viewportProps?: HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  "data-line-numbers"?: boolean;

  /**
   * @defaultValue 1
   */
  "data-line-numbers-start"?: number;

  Actions?: (props: { className?: string; children?: ReactNode }) => ReactNode;
}

const TabsContext = createContext<{
  containerRef: RefObject<HTMLDivElement | null>;
  nested: boolean;
} | null>(null);

export function Pre(props: ComponentProps<"pre">) {
  return (
    <pre
      {...props}
      className={cn("min-w-full w-max *:flex *:flex-col", props.className)}
    >
      {props.children}
    </pre>
  );
}

export function CodeBlock({
  ref,
  title,
  allowCopy = true,
  keepBackground = false,
  icon,
  viewportProps = {},
  children,
  Actions = (props) => (
    <div {...props} className={cn("empty:hidden", props.className)} />
  ),
  ...props
}: CodeBlockProps) {
  const inTab = useContext(TabsContext) !== null;
  const areaRef = useRef<HTMLDivElement>(null);
  const railRef = useRef<HTMLDivElement>(null);
  const syncLockRef = useRef(false);
  const [railWidth, setRailWidth] = useState(0);

  useEffect(() => {
    const area = areaRef.current;
    const rail = railRef.current;
    if (!area || !rail) return;

    const syncFromArea = () => {
      if (syncLockRef.current) return;
      syncLockRef.current = true;
      rail.scrollLeft = area.scrollLeft;
      syncLockRef.current = false;
    };

    const syncFromRail = () => {
      if (syncLockRef.current) return;
      syncLockRef.current = true;
      area.scrollLeft = rail.scrollLeft;
      syncLockRef.current = false;
    };

    const updateMetrics = () => {
      setRailWidth(area.scrollWidth);
      rail.scrollLeft = area.scrollLeft;
    };

    updateMetrics();
    area.addEventListener("scroll", syncFromArea, { passive: true });
    rail.addEventListener("scroll", syncFromRail, { passive: true });
    window.addEventListener("resize", updateMetrics);

    const observer = new ResizeObserver(updateMetrics);
    observer.observe(area);
    const pre = area.querySelector("pre");
    if (pre) observer.observe(pre);

    return () => {
      area.removeEventListener("scroll", syncFromArea);
      rail.removeEventListener("scroll", syncFromRail);
      window.removeEventListener("resize", updateMetrics);
      observer.disconnect();
    };
  }, [children, title]);

  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      className={cn(
        inTab ? "bg-fd-secondary -mx-px -mb-px" : "my-2 bg-fd-card",
        keepBackground && "bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)",
        "group shiki relative border border-brand-neutral-500 bg-brand-black/60 outline-none not-prose overflow-hidden text-sm rounded-sm",
        props.className
      )}
    >
      {title ? (
        <div className="flex items-center gap-2 h-10 border-b px-4 border-brand-neutral-500 text-brand-neutral-100">
          {typeof icon === "string" ? (
            <div
              className="[&_svg]:size-3.5"
              dangerouslySetInnerHTML={{
                __html: icon,
              }}
            />
          ) : (
            icon
          )}
          <figcaption className="flex-1 truncate">{title}</figcaption>
          {Actions({
            className:
              "-me-2 opacity-0 transition-opacity duration-200 pointer-events-none group-hover:opacity-100 group-hover:pointer-events-auto group-focus-within:opacity-100 group-focus-within:pointer-events-auto",
            children: allowCopy && (
              <CopyButton
                containerRef={areaRef}
                className="top-0 right-0.5 [&_button]:rounded-xs [&_button]:border [&_button]:border-brand-neutral-300 [&_button]:bg-brand-neutral-600 [&_button]:shadow-sm"
              />
            ),
          })}
        </div>
      ) : (
        Actions({
          className:
            "absolute top-2 right-2 z-2 backdrop-blur-lg rounded-lg text-fd-muted-foreground opacity-0 transition-opacity duration-200 pointer-events-none group-hover:opacity-100 group-hover:pointer-events-auto group-focus-within:opacity-100 group-focus-within:pointer-events-auto",
          children: allowCopy && (
            <CopyButton
              containerRef={areaRef}
              className="[&_button]:rounded-xs [&_button]:border [&_button]:border-brand-neutral-300 [&_button]:bg-brand-neutral-600 [&_button]:shadow-sm"
            />
          ),
        })
      )}
      <div className="flex flex-col">
        <div
          ref={areaRef}
          {...viewportProps}
          className={cn(
            "text-[13px] py-3 overflow-auto max-h-[600px] sidebar-scrollbar",
            viewportProps.className
          )}
          style={
            {
              // space for toolbar
              "--padding-right": !title
                ? "calc(var(--spacing) * 8)"
                : undefined,
              counterSet: props["data-line-numbers"]
                ? `line ${Number(props["data-line-numbers-start"] ?? 1) - 1}`
                : undefined,
              ...viewportProps.style,
            } as object
          }
        >
          {children}
        </div>
        <div
          ref={railRef}
          className="codeblock-scroll-rail h-4 overflow-x-auto overflow-y-hidden border-t border-brand-neutral-500 bg-brand-neutral-600/60"
        >
          <div
            className="h-px"
            style={{
              width: `${railWidth}px`,
              minWidth: "100%",
            }}
          />
        </div>
      </div>
    </figure>
  );
}

function CopyButton({
  className,
  containerRef,
}: {
  containerRef: RefObject<HTMLElement | null>;
  className?: string;
}) {
  const [text, setText] = useState("");

  useEffect(() => {
    const pre = containerRef.current?.getElementsByTagName("pre").item(0);
    if (!pre) return;

    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
      node.replaceWith("\n");
    });

    setText(clone.textContent ?? "");
  }, [containerRef]);

  return (
    <CustomCopyButton
      text={text}
      className={cn("size-6 top-2 right-0.5", className)}
    />
  );
}
